[package]
name = "problem1914"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]
name = "p1914a"
path = "src/problem1914a.rs"

[[bin]]
name = "p1914b"
path = "src/problem1914b.rs"

[[bin]]
name = "p1914c"
path = "src/problem1914c.rs"
